import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_components/Navbar";
import ConvexClientProvider from "./ConvexClientProvider";
// import FilterContextProvider from "./Context/FilterContext"
import ConnectUserToConvex from "./ConnectUsertoConvex";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
      <ClerkProvider>
          <Navbar/>
           {/* <FilterContextProvider> */}
            <ConnectUserToConvex/>
          {children}
           {/* </FilterContextProvider> */}
          </ClerkProvider>
          </ConvexClientProvider>
      </body>
    </html>
  );
}
